### ISSUE TITLE
A way to instruct a specific OAI example response

### ISSUE THREAD

**Issue by goldbergyoni** [outofcoffee/imposter#470]
Say I have some route that is documented with two examples in OpenAPI. For example, a User schema, sometimes it might return isDeleted=false, in other cases isDeleted=true

From within a test, I'd like to influence the mocked response and trigger isDeleted=true

Is this doable? appreciate a link to the relevant docs section

**Comment by outofcoffee** [comment]
Hi @goldbergyoni, thanks for your question. You can choose the OpenAPI example to return by name by using the `response.exampleName` property described here:
https://docs.imposter.sh/openapi_plugin/#overriding-examples

Something like this:

```yaml
plugin: "openapi"
specFile: "spec-with-multiple-examples.yaml"

resources:
  - path: /users/:id
    method: get
    pathParam:
      id: foo
    response:
      exampleName: userExample1

  - path: /users/:id
    method: get
    pathParam:
      id: bar
    response:
      exampleName: userExample2
```

The `userExample1` and `userExample2` names would correspond to named `examples` for this operation in your OpenAPI spec.

Hope this helps!
