### ISSUE TITLE
Using Expression.regexify in content responses

### ISSUE THREAD

**Issue by acsauk** [outofcoffee/imposter#519]
Hey there - I'm trying to avoid writing a custom script to use [regexify](https://github.com/datafaker-net/datafaker?tab=readme-ov-file#expressions) to return some dynamic content for an endpoint but can't see how (or if it's possible). Following the examples in the [imposter docs](https://github.com/outofcoffee/imposter/blob/main/docs/fake_data.md) around things like `fake.Name.firstname` I've tried to do:

```yaml
path: "/cases"
response:
  template: true
  content: | 
    {"uid": "${fake.Expression.regexify 'M-([346789QWERTYUPADFGHJKLXCVBNM]{4})-([346789QWERTYUPADFGHJKLXCVBNM]{4})-([346789QWERTYUPADFGHJKLXCVBNM]{4})'}"}
```  

and some variations on the function calls (e.g. `fake.Expression.regexify(<REGEX>)`, `fake.regexify <REGEX>` etc) which results in:

```
java.lang.RuntimeException: Unable to resolve #{Expression.regexify 'M-([346789QWERTYUPADFGHJKLXCVBNM]{4}} directive for FakerContext FakerContext{, locale=net.datafaker.internal.helper.SingletonLocale@e453b2f1, randomService=net.datafaker.service.RandomService@574c8457}.
```

Is this something imposter supports inline in the config or should I be reaching for a script instead?

**Comment by outofcoffee** [comment]
Hi @acsauk, thanks for asking this. One option that might work for you is the `${random.any(chars="...")}` function added in [v3.34.0](https://github.com/outofcoffee/imposter/releases).

For example:

```yaml
path: "/cases"
response:
  template: true
  content: | 
    {"uid": "M-${random.any(chars="346789QWERTYUPADFGHJKLXCVBNM", length=4)}-${random.any(chars="346789QWERTYUPADFGHJKLXCVBNM", length=4)}-${random.any(chars="346789QWERTYUPADFGHJKLXCVBNM", length=4)}"}
```
