### ISSUE TITLE
Let a percentage of requests fail

### ISSUE THREAD

**Issue by neugartf** [outofcoffee/imposter#526]
Hi, love the project! :)

Quick question: what would be the easiest way to let 10% of the requests of an OpenAPI document fail?
There is of course this functionality: https://docs.imposter.sh/failure_simulation/. I checked the code and it looks like there is no option for this (yet).  Should that rather be a new plugin or should the core functionality extended? 

👋

**Comment by outofcoffee** [comment]
Hi @neugartf, thanks for raising this.

You can have a percentage of responses fail, or use a particular status code by using a script step.

Here's a simple example:

```yaml
---
plugin: openapi
specFile: petstore.yaml

resources:
  - path: /pets
    steps:
      - type: script
        code: |
          if (Math.random() < 0.5) {
            respond().withStatusCode(500);
          } else {
            respond().withStatusCode(200);
          }
```

Here's a full example: https://github.com/outofcoffee/imposter/tree/main/examples/openapi/response-error-percentage
