### ISSUE TITLE
Autoreload when using docker and config files change

### ISSUE THREAD

**Issue by rnestler** [outofcoffee/imposter#553]
I mount the configuration via volume into the imposter docker container using the following docker-compose.yml:
```yaml
services:
  imposter:
    image: outofcoffee/imposter-all:3.36.2
    container_name: imposter
    volumes:
      - ./imposter_config:/opt/imposter/config
    ports:
      - 127.0.0.1:8080:8080
``` 

Now every time I make changes to the configuration I need to restart the docker container. While I can automate this with `fswatch --event Updated --event Removed --event Created -or imposter_config/ | xargs -I{} docker compose restart` it takes quite some time until the docker container is restarted and ready again.

Is there some easy way to enable auto reloading whenever the configuration changed?
