### ISSUE TITLE
Question about mocking multiple path and sub arrays

### ISSUE THREAD

**Issue by cscetbon** [outofcoffee/imposter#58]
From https://github.com/outofcoffee/imposter/blob/master/docs/rest_plugin.md#multiple-paths I understand that I can access element from an array like the examples of cats and dogs. however what if the array element also contains an array

Imagine I want to mock a call like `cats/:id/owners` and `cats/:id/owners/:ownerid`. where the first one would return the full array and the second only a specific owner using its id.

How can I mock a rest api like this one ?

**Comment by cscetbon** [comment]
Also what happens when I have something like 
```
  - path: "cats/:id/owners/:ownerid"
    type: array
    response:
      staticFile: owners.json
```
What does imposter try to do ? cause I get `HTTP/1.1 404 Not Found` when I try to query some couples of (id, ownerid) but not sure what it does exactly, what look ups it does.
