### ISSUE TITLE
Access Denied on file write for POST x-www-form-urlencoded request

### ISSUE THREAD

**Issue by b0g3r** [outofcoffee/imposter#59]
First of all: this project is awesome and it saves us a lot of time. I really appreciate your work 🙌 

We have a config for `POST /` request, it emulates [Amazon STS Assume Role](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) endpoint, so it looks like this:

```yaml
---
plugin: rest
resources:
  - path: "/"
    method: POST
    response:
      staticData: |
        <AssumeRoleResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
        ...
```

Locally we don't have any problem but when we try it in the Kubernetes cluster we started to see 500 Internal Errors with the exception of about access denied, vertx, and `/file-uploads`. I think it is because in our Pod we usually have a read-only filesystem, but Imposter tries to write something into it.

It is reproduced only with `application/x-www-form-urlencoded` in Content-Type and on a read-only filesystem, so it is my example of a request:

```python
In [23]: httpx.post('http://imposter').content
Out[23]: b'<AssumeRoleResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">\n...\n'

In [24]: httpx.post('http://imposter',headers={'Content-Type': b'application/x-www-form-urlencoded; charset=utf-8'}).content
Out[24]: b'Internal Server Error'
```
