### ISSUE TITLE
Mock Calls for All Values of a Path Parameter

### ISSUE THREAD

**Issue by daniel-klingensmith-jamf** [outofcoffee/imposter#616]
Hello,

I'm trying to respond with mocks for all calls made to an endpoint with a path paramter, the value of which isn't known at code time. I am trying the following usage of `operator: Exists` but the config file isn't loading.

Partial Config:
```
  # handles GET /customer/v1/tenants/*/state
  - method: GET
    path: "/customer/v1/tenants/:tenantId/state"
    pathParams:
      tenantId:
        operator: Exists
    response:
      file: state.json
```
Partial Stacktrace
```
Caused by: java.lang.RuntimeException: Error loading configuration file: /tmp/s3-mock-machine-bucket1511021055925037033/jsc-mocks-config.yaml, reason: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
 at [Source: (StringReader); line: 29, column: 9] (through reference chain: io.gatehill.imposter.plugin.rest.config.RestPluginConfig["resources"]->java.util.ArrayList[1]->io.gatehill.imposter.plugin.rest.config.RestPluginResourceConfig["pathParams"]->java.util.LinkedHashMap["tenantId"])
	at io.gatehill.imposter.config.util.ConfigUtil.loadPluginConfig(ConfigUtil.kt:320)
	at io.gatehill.imposter.plugin.config.ConfiguredPlugin.loadConfiguration(ConfiguredPlugin.kt:74)
	... 9 more
```

**Comment by outofcoffee** [comment]
Hi @daniel-klingensmith-jamf, thanks for raising this.

Please could you confirm which version of Imposter you're using?

**Comment by daniel-klingensmith-jamf** [comment]
@outofcoffee  I'm using 3.35.0 via uploading the .zip file to S3

**Comment by outofcoffee** [comment]
Hi @daniel-klingensmith-jamf, thank you for confirming.

The extended format for path parameters (and query parameters, form fields and headers) was added in [v3.36.0](https://github.com/outofcoffee/imposter/releases/tag/v3.36.0).

If you're able to use a [more recent version](https://github.com/outofcoffee/imposter/releases/) this syntax is supported.

**Comment by daniel-klingensmith-jamf** [comment]
I've verified this works on 4.0.3, however the following no longer works:
```
   - method: GET
     path: "/v1/cloud-instances/:cloudInstanceId"
     pathParams:
       cloudInstanceId: 000000000000004101
     response:
       file: cloudInstance-000000000000004101.json
```
It's not a big deal for me though since I've updated my code to the new syntax.

**Comment by daniel-klingensmith-jamf** [comment]
However, I'm unable to get `queryParams` to work.
```
  - method: GET
    path: "/v1/assets-and-licenses"
    queryParams:
      accountId: 1001
    response:
      file: account-1001.json
```
Request:
`https://<lambda>.lambda-url.us-east-1.on.aws/v1/assets-and-licenses?accountId=1001`

Imposter Logs:
```
DEBUG i.g.i.p.r.RestPluginImpl - Adding handler: GET -> /v1/assets-and-licenses
…
i.g.i.a.AbstractHandler - Received request: GET /v1/assets-and-licenses
i.g.i.p.r.RestPluginImpl - Handling object request for: GET http://<lambda>.lambda.lambda-url.us-east-1.on.aws/v1/assets-and-licenses
i.g.i.s.ResponseServiceImpl - Response file and data are blank for [84c11c84-dbf0-445d-b46e-976b0cd36aa0] GET http://<lambda>.lambda.lambda-url.us-east-1.on.aws/v1/assets-and-licenses
i.g.i.s.ResponseServiceImpl - Returning empty response for [84c11c84-dbf0-445d-b46e-976b0cd36aa0] GET http://<lambda>.lambda.lambda-url.us-east-1.on.aws/v1/assets-and-licenses
```
